# Generated by Django 6.0.7 on 2026-08-01 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the note title', max_length=200)),
                ('content', models.TextField(help_text='Enter the content of the note.', max_length=600, validators=[django.core.validators.MaxLengthValidator(1500)])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
